### ISSUE TITLE
IncreaseHealth at step 13

### ISSUE THREAD

**Issue by ghostbullet** [gepthecoder/game-hacking#1]
IncreaseHealth at step 13, as I see this function return void, do you return 999 is that correct?

**Comment by gepthecoder** [comment]
No, thanks for pointing this out! 👍🏼 you should ideally find a getter method that returns an integer for this case and make it always return 999 (money hack for example)

**Comment by ghostbullet** [comment]
Yes, I see. Looking for int return method from start, then I see your return int in void method then I tried once xD You should replace that picture for good measure

**Comment by ghostbullet** [comment]
One more thing, at function start public void SetLevel(int level), function have to load level param, I tried to replace the line that load param from stack (str x30, [sp, #-0x10]!) with move direct an integer value into that (as movz x30, #555), after that the game crash when call to this function. Does this way always make game crash?

**Comment by gepthecoder** [comment]
The game could potentially crash if you disrupted some mechanics yes.
